version: '3'
services:
  web:
    image: hapka-website
    build: .
    ports:
      - "80:80"
      - "443:443"
    container_name: nginx
    volumes:
      - ./html:/usr/share/nginx/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - ./ssl:/etc/nginx/ssl